- name: test
  hosts: server_ubuntu
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes

    - name: copy HTML
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
